export const ICONS = {
	prayer_location_icon: require("../assets/icons/prayer_location_icon.png"),
	next_prayer_icon: require("../assets/icons/next_prayer_icon.png"),
	prayer_times_icon: require("../assets/icons/clock_icon.png"),
	dhikr_icon: require("../assets/icons/dhikr_icon.png"),
	qibla_icon: require("../assets/icons/qibla_icon.png"),
	schedule_icon: require("../assets/icons/schedule_icon.png"),
	settings_icon: require("../assets/icons/settings_icon.png"),
	reset_icon: require("../assets/icons/reset_icon.png"),
	hand_icon: require("../assets/icons/hand_icon.png"),
	intro_arrow: require("../assets/icons/intro_arrow.png"),
	intro_location: require("../assets/icons/intro_location.png"),
	intro_notification: require("../assets/icons/intro_notification.png"),
	search_icon: require("../assets/icons/search_icon.png"),
	right_arrow_icon: require("../assets/icons/right_arrow_icon.png"),
	account_icon: require("../assets/icons/account_icon.png"),
	notification_icon: require("../assets/icons/notification_icon.png"),
	privacy_icon: require("../assets/icons/privacy_icon.png"),
	support_icon: require("../assets/icons/support_icon.png"),
	appearence_icon: require("../assets/icons/appearence_icon.png"),
	about_icon: require("../assets/icons/about_icon.png"),
	left_arrow_icon: require("../assets/icons/left_arrow_icon.png"),
	close_icon: require("../assets/icons/close_icon.png"),
	prayer_notification: require("../assets/icons/prayer_notification.png"),
	prayer_notification_active: require("../assets/icons/prayer_notification_active.png"),
};
