export const KEHF = {
	alb: {
		0: "Me emrin e All-llahut, Mëshiruesit, Mëshirëbërësit!",
		1: "Falënderimi i takon vetëm All-llahut që ia shpalli robit të vet Librin dhe në të nuk lejoi ndonjë kundërthënie.",
		2: "(ia shpalli) Të saktë (pa shmangie), pëR t'ua tërhequr vërejtjen (atyre që nuk besojnë) ndaj një dënimi të rëndë prej Tij, e për t'i përgëzuar besimtarët që bëjnë vepra të mira, se ata do të kenë një shpërblim të mrekullueshëm.",
		3: "Duke qenë në të përgjithmonë.",
		4: "Për t'ua tërhequr vërejtjen atyre që thanë se All-llahu ka fëmijë.",
		5: "Dhe për atë (fëmijë), as ata, e as të parët e tyre nuk kanë kurrfarë dijenie. Sa e madhe është ajo fjalë që del nga gojët e tyre, e ata nuk thonë tjetër vetëm se gënjeshtër.",
		6: "A thua ti, do ta shkatërrosh veten nga hidhërimi pas tyre, nëse ata nuk i besojnë këtij ligjërimi (Kur’anit)?",
		7: "Gjithçka që është mbi tokë, Ne e bëmë stoli të saj, për t'i provuar ata, se cili prej tyre do të jetë më vepërmirë.",
		8: "Ne kemi për ta bërë gjithçka që është mbi të dhé pa bimë (shkatërrojmë çdo gjelbërim).",
		9: "A mos mendove ti se ata të vendosurit e shpellës dhe Rekimit ishin nga mrekullitë Tona më të çuditshme?",
		10: "Kur djelmoshat u strehuan në shpellë e thanë: 'O Zoti ynë, na dhuro nga ana Jote mëshirë dhe na përgatit udhëzim të drejtë në tërë çështjen tonë!'",
		11: "Ne u vumë mbulojë mbi veshët e tyre (i vumë në gjumë) në shpellë për disa vite me radhë.",
		12: "Pastaj ata i zgjuam (prej gjumit) për të parë se cili prej atyre dy grupeve është më preciz në njehsimin e kohës sa qëndruan gjatë",
		13: "Ne po të rrëfejmë saktë çështjen e tyre. Ata ishin disa djelmosha, kishin besuar Zotin e tyre, e Ne atyre edhe më ua shtuam bindjen.",
		14: "Edhe i forcuam zemrat e tyre (i bëmë të qëndrueshëm) saqë kur u ngritën, thanë: 'Zoti ynë është Zot i qiejve e i tokës, nuk adhurojmë ndonjë zot tjetër pos Tij', pse atëherë do të thoshim diçka shumë mizore!",
		15: "Këta, populli ynë ka besuar zota të tjerë pos Atij, pse pra nuk sjellin ndonjë argument të qartë për ata? A ka më mizor se ai që shpif gënjeshtër ndaj All-llahut?",
		16: "Derisa jeni izoluar prej tyre dhe prej asaj që adhurojnë ata, pos All-llahut, atëherë strehohuni në shpellë, e Zoti juaj ju dhuron nga mëshira e tij e gjerë dhe ju lehtëson në çështjen tuaj atë që është në dobinë tuaj.",
		17: "Dhe ti e shihje diellin, kur lindte bartej prej shpellës së tyre nga ana e djathtë, e kur perëndonte largohej nga ata nga ana e majtë, e ata ishin në një vend të gjerë të saj. Kjo ishte një nga argumentet e All-llahut. Atë që e udhëzon All-llahu, ai vërtet është udhëzuar, e atë që e humb, ti nuk do të gjesh për të ndihmës që do ta udhëzonte.",
		18: "Do të mendoje se ata janë të zgjuar, ndërsa ata ishin të fjetur, e Ne i rrotullonim herë në krahun e djathtë e herë në të majtin. Qeni i tyre i kishte shtrirë këmbët e para pranë hyrjes. Sikur të kishe hasur në ta, do të ishe kthyer duke ikur dhe do të ishe mbushur frikë prej tyre.",
		19: "Ashtu (sikurse i vumë në gjumë) i zgjuam ata që të pyesin njëri-tjetrin (se sa kanë fjetur). Njëri prej tyre foli e tha: 'Sa keni ndejur?' Ata thanë:'Kemi ndejur një ditë ose një pjesë të ditës!' Disa thanë: 'Zoti juaj e di më së miri se sa keni ndejur, prandaj dërgojeni njërin prej jush me këtë argjend (monedhë argjendi) në qytet, e të zgjedhë ushqim më të mirë, e t'ua sjellë atë juve dhe le të ketë shumë kujdes e të mos i japë të kuptojë askujt për ju'.",
		20: "Pse, nëse ata (të qytetit) kuptojnë për ju, do t'ju mbysin me gurë, ose do t'ju kthejnë në fenë e tyre, e atëherë kurrë nuk keni për të shpëtuar.",
		21: "Dhe ashtu (sikurse i zgjuam nga gjumi) i zbuluam (t'i shohin njerëzit), e të kuptojnë se premtimi i All-llahut (për ringjallje) është i sigurt dhe se katastrofa e përgjithshme (kijameti) është e padyshimtë. (I zgjuam) Mu atëherë kur ata (populli) bisedonin për çështjen e tyre dhe thanë: 'Ndërtojuni atyre një ndërtesë (të jetë shenjë). Zoti i tyre di më së miri për ta.' E ata që ishin me shumicë thanë: 'Do të ndërtojmë gjithqysh në hyrjen e tyre një xhami'.",
		22: "Ata (që bisedonin për këtë) do të thonë: 'Ishin tre, i katërti i tyre ishte qeni i tyre', dhe thonë: 'Ishin pesë, e qeni i tyre ishte i gjashti i tyre', kjo ishte hamendje, po edhe thonë: 'Ishin shtatë, e qeni i tyre ishte i teti!' Thuaj: 'Zoti im di më së miri për numrin e tyre, përveç një pakice nuk di kush për ta, e ti (Muhammed) mos polemizo për numrin e tyre vetëm ashtu në tërësi, dhe askë mos pyet për ta'.",
		23: "Dhe mos thuaj kurrsesi për ndonjë çështje: 'Unë do ta bëj këtë nesër!'",
		24: "Vetëm (nëse i shton): 'Në dashtë All-llahu!' E kur të harrosh, përmende Zotin tënd dhe thuaj: 'Shpresohet se Zoti im do të më japë udhëzim edhe më të afërt prej këtij (të as-habi kehfit)'",
		25: "(dhe thonin) Ata qëndruan në shpellën e tyre treqind e nëntë vjet.",
		26: "Thuaj: 'All-llahu e di më së miri sa kanë ndejur, Atij i takon fshehtësia e qiejve dhe e tokës. Çfarë (i çuditshëm) është të pamurit e Tij dhe çfarë është të dëgjuarit e Tij! Pos Tij ata (njerëzit) nuk kanë ndihmëtarë. Në vendimin e Tij nuk mund t'i përzihet askush'.",
		27: "Lexo çka të është shpallur ty nga libri i Zotit tënd! Nuk ka kush që mund t'i ndryshojë fjalët e Tij dhe pos Tij, nuk mund të gjesh strehim.",
		28: "Përkufizoje veten tënde me ata që lusin Zotin e tyre mëngjes e mbrëmje, e që kanë për qëllim kënaqësinë (razinë) e Tij, dhe mos i hiq sytë e tu prej tyre e të kërkosh bukurinë e kësaj bote dhe mos iu bind atij që ia kemi shmangur zemrën e tij prej përkujtimit ndaj Nesh dhe i është dhënë epshit të vet, pse puna e tij ka mbaruar.",
		29: "E ti thuaj: 'E vërteta është nga Zoti juaj, e kush të dojë, le të besojë, e kush të dojë, le të mohojë. Ne kemi përgatitur për jobesimtarët zjarr që muret e tij (të flakës) i rrethojnë ata, e nëse kërkojnë shpëtim, ndihmohen me një ujë si katran që përzhit fytyrat. E shëmtuar është ajo pije, e vend i keq është ai'.",
		30: "E ata që besuan dhe bënë vepra të mira, s'ka dyshim se Ne nuk i humbim shpërblimin atij që është bamirës.",
		31: "Të tillët e kanë vendin në xhennetin e Adnit, nën të cilin rrjedhin lumenj; e aty stolisen me rrathë të artë dore dhe ata veshin rroba të gjelbra prej mëndafshi të hollë e të trashë, janë mbështetur aty në shtretër. Sa shpërblim i mrekulleshëm është dhe sa vend i bukur është ai.",
		32: "E ti sillu atyre (që kërkuan t'i largosh varfanjakët) si shembul dy njerëz; njërit prej tyre i dhamë dy kopshte (vreshta) nga rrushi dhe ato i rrethuam me hurma, e në mes atyre dujave bimë të tjera.",
		33: "Të dy kopshtet jepnin frutat e veta pa munguar prej tyre asgjë, e në mesin e tyre bëmë të rrjedhë një lumë.",
		34: "Ai kishte edhe pasuri tjetër. E ai atij shokut të vet (që ishte besimtar) i tha: - duke iu krenuar atij - 'Unë kam pasuri më shumë se ti e, kam edhe krah më të fortë!'",
		35: "Dhe ai hyri në kopshtin e vet (e me besimtarin për dore), po duke qenë dëmtues i vetes (duke mos besuar dhe duke u krenuar) tha: 'Unë nuk mendoj se zhduket kjo kurrë!'",
		36: "'Dhe nuk besoj se do të ndodhë kijameti, (dita e gjykimit), por nëse bëhet që të kthehem te Zoti im, pa dyshim do të gjej ardhmëri edhe më të mirë se kjo'",
		37: "Atij ai shoku i vet (besimtari) i tha - duke e polemizuar atë - 'A e mohove Atë që të krijoi ty nga dheu, pastaj nga një pikë uji, pastaj të bëri njeri të plotë?'",
		38: "'Por për mua, Ai All-llahu është Zoti im, e Zotit tim unë nuk i bëj shok askë!'",
		39: "E pse ti kur hyre në kopshtin tënd nuk the: 'Ma shaell llah, la kuvvete il-la bil-lah' - (All-llahu çka do, bëhet, s'ka fuqi pa ndihmën e Tij). Nëse ti më sheh mua se unë kam më pak prej teje edhe pasuri edhe fëmijë (krah më të dobët).",
		40: "Po unë shpresoj se Zoti im do të më japë edhe më të mirë nga kopshti yt, e këtij tëndit t'i shkaktojë fatkeqësi nga qielli e të gdhijë tokë e lëmuar (e zhveshur).",
		41: "Ose të gdhijë uji i saj i shterur, e ti kurrsesi nuk mund ta kërkosh atë!",
		42: "Dhe vërtet, u shkatërruan frutat e tij, e ai filloi të rrahë shuplakët për atë që kishte shpenzuar në të, e ajo ishte rrënuar në kulmet e saj dhe thoshte: 'O i mjeri unë, të mos i kisha bërë Zotit tim askë shok'",
		43: "E nuk pati krah (grup), pëveç All-llahut të vërtetë që t'i ndihmojë atij dhe nuk mundi ta pengojë.",
		44: "Në atë vend ndihma është vetëm e All-llahut të vërtetë. Ai është shpërblyesi më i mirë dhe te Ai është përfundimi më i mirë.",
		45: "E ti (Muhammed) paraqitjau atyre shembullin e kësaj bote që është si një ujë (shi) që Ne e lëshojmë nga qielli, e prej tij bima e tokës zhvillohet e shpeshtohet saqë përzihet mes vete, e pas pak ajo bëhet byk (pas tharjes) që e shpërndajnë erërat. All-llahu ka fuqi për çdo send.",
		46: "Pasuria dhe fëmijët janë stoli e jetës së kësaj bote, kurse veprat e mira (fryti i të cilave është i përjetshëm) janë shpërblimi më i mirë te Zoti yt dhe janë shpresa më e mirë.",
		47: "(Përkujto) Ditën kur Ne i shkulim kodrat, dhe tokën e sheh të sheshtë (të zbuluar) dhe Ne i tubojmë ata e nuk na mbetet asnjë prej tyre pa e tubuar.",
		48: "Dhe ato do të prezentohen para Zotit tënd të rreshtuar (e u thuhet atyre): 'Na erdhët ashtu, si ju krijuam juve herën e parë, por ju patët menduar se Ne nuk kemi caktuar për ju ringjallje'.",
		49: "Dhe vihet libri (i veprave), e i sheh mëkatarët të frikësuar nga shënimet që janë në të dhe thonë: 'Të mjerët ne, ç'është puna e këtij libri që nuk ka lënë as (mëkat) të vogël e as të madh pa e përfshirë?', dhe atë që vepruan e gjejnë të gatshme - prezente, e Zoti yt nuk i bën padrejt askujt.",
		50: "(Përkujto) Kur u thamë engjëjve: 'Përuluni Ademit, e ata iu përulën përpos Iblisit. Ai ishte nga xhinët, prandaj nuk respektoi urdhrin e Zotit të vet. Vallë, a në vend Timin do ta merrni për mik atë dhe pasardhësit e tij, ndërsa ata janë armiq tuaj?' Sa këmbim i shëmtuar është ai i jobesimtarëve!",
		51: "Unë nuk ua prezentova krijimin e qiejve e të tokës atyre që po i adhuroni e as krijimin e vetë atyre, e as nuk mora ndihmëtarë të humburit.",
		52: "E ditën kur Ai thotë: 'Thirrni ata, për të cilët menduat se janë bashkëpunëtorët e Mi!' I thërrasin, por ata nuk u përgjigjen (për ndihmë) atyre dhe ato lidhjet e tyre (në Dunja) Ne i zhdukim.",
		53: "Kriminelët e shohin zjarrin dhe binden se do të hidhen në të, dhe se nuk gjejnë shtegdalje prej tij.",
		54: "Në këtë Kur'an Ne shtruam çdo lloj shembulli për hir të njerëzve, po njeriu (jobesimtar) më shumë se çdo tjetër është kundërshtar.",
		55: "Pasi që t'u ketë ardhur udhëzimi, njerëzit nuk i pengoi tjetër të besojnë dhe të kërkojnë falje prej Zotit të tyre, vetëm se presin t'u vijë edhe atyre fatkeqësia e popujve të mëparshëm ose t'u vijë atyre dënimi ballë për ballë.",
		56: "Ne nuk i dërgojmë ndryshe të dërguarit pos vetëm si përgëzues e qortues. E, megjithatë, ata që nuk besuan polemizojnë me të pavërtetën në mënyrë që me të, ta mbizotërojnë të vërtetën, dhe argumentet e Mia dhe atë me çka u qortuan i marrin për tallje.",
		57: "Kush është më zullumqar se ai që është këshilluar me argumentet e Zotit të vet, e ua kthen shpinën atyre dhe harron atë që vetë e punoi? Ne kemi vënë mbi zemrat e tyre mbulesë në mënyrë që të mos e kuptojnë atë (Kur'anin), kurse në veshët e tyre shurdhim, andaj edhe nëse i thërret ti ata në rrugë të drejtë, ata si të tillë nuk do të udhëzohen kurrë.",
		58: "Zoti yt është që falë shumë dhe bën mëshirë të madhe, sikur t'i ndëshkonte ata për atë që kanë vepruar, do t'ua ngutte atyre tash dënimin, por ata kanë momentin e caktuar, e pos Tij nuk do të gjejnë ata strehim.",
		59: "Ato janë fshatra (vendbanime) që kur bënë zullum, Ne i shkatërruam dhe për shkatërrimin e tyre u patëm caktuar kohë të sakta.",
		60: "(përkujto) Kur Musai djaloshit që e shoqëronte i tha: 'Nuk do të ndalem së ecuri deri ta arrij vendtakimin e dy deteve, ose do të udhëtoj një kohë të gjatë'.",
		61: "Kur arritën ata të dy vendtakimin e atyre deteve, e harruan peshkun e tyre, e ai (peshku) mori rrugën e vet si (strofull) në det.",
		62: "Pasi ata e kaluan atë vend, ai (Musai) i tha djaloshit: 'Na jep sillën tonë (ushqimin), meqë nga ky udhëtim jemi lodhur'.",
		63: "Ai (djaloshi - Jushaë bin Nun) tha: 'A e sheh!? Kur u strehuam te shkëmbi, unë e harrova peshkun dhe përveç djallit nuk më bëri kush të harrojë që të ta përkujtoj ty atë, dhe ai në mënyrë të çuditshme mori rrugën e tij për në det!'",
		64: "Ai (Musai) tha: 'Ai është (vendi) që ne po e kërkojmë!' Dhe u kthyen që të dy rrugës së tyre prej nga kishin ardhur.",
		65: "Dhe e gjetën një nga robtë Tanë, të cilit i kemi dhuruar mëshirë nga ana Jonë dhe e kemi mësuar me një dituri të posaçme nga Ne.",
		66: "Atij (Hidrit - njeriut të mirë e të dijshëm) Musai i tha: 'A pranon të vijë me ty, që të më mësosh nga ajo që je i mësuar (i dhuruar) ti: dituri të drejtë e të vërtetë?'",
		67: "Ai (Hidri) tha: 'Sigurisht, ti nuk do të mund të kesh durim me mua!'",
		68: "'Si do të durosh për atë që nuk je i njoftuar?'",
		69: "(Musai) Tha: 'Në dashtë All-llahu, do të shohësh se do të jem i durueshëm dhe nuk do të kundërshtoj ty për asgjë!'",
		70: "Ai i tha: 'Nëse më shoqëron ti mua, atëherë mos më pyet për asgjë, derisa unë vetë të të tregoj për të'.",
		71: "E ata të dy shkuan (duke ecur) deri kur hipën në anije, ai (i dishmi) e shqeu atë. Ai (Musai) tha: 'A e shqeve që t'i fundosësh udhëtarët e saj, vërtet bëre një punë të hatashme?'",
		72: "Tha: 'A nuk të thashë se nuk do të mund të kesh durim me mua?'",
		73: "(Musai) Tha: 'Mos më qorto përse harrova dhe mos më mundo me vështirësi në këtë shoqërim timin (lehtësoma punën)!'",
		74: "Vazhduan të shkojnë deri kur takuan një djalë të ri, e ai (i dijshmi) e mbyti atë. (Musai) Tha: 'A e mbyte njeriun e pastër, pa mbytur ai askë?! Vërtet ke bërë një pumë të shëmtuar!'",
		75: "Ai (i dijshmi) tha: 'A nuk të thashë se vërtet ti nuk do të mund të kesh durim me mua?'",
		76: "(Musai) Tha: 'Nëse pas kësaj të pyes (të kundërshtoj) për ndonjë gjë, atëherë mos më lejo të shoqëroj. Tashmë ndaj meje ke arsyetim (të mos më shoqërosh)!'",
		77: "Vazhduan të shkojnë deri sa arritën te banorët e një qyteti që prej tyre kërkuan t'u japin ushqim, po ata nuk deshën t'i pranojnë si musafirë (e as t'i ushqejnë), e ata të dy gjetën aty një mur që gati po rrëzohej, e ai e drejtoi atë (murin). (Musai) Tha: 'Sikur të kishe dashur do t'u merrje shpërblim për këtë!",
		78: "Ai (i dijshmi) tha: 'Tash ka ardhur koha e ndarjes mes meje dhe mes teje, e unë do të tregoj për domethënien e asaj që nuk munde të keshë durim!'",
		79: "Sa i përket anijes, ajo ishte pronë e do të varfërve që veprojnë në det, e unë desha ta bëj atë me të meta, ngase para tyre ishte një sundues që grabiste çdo anije (të aftë - pa të meta).",
		80: "Sa i përket djaloshit, dy prindërit e tij ishin besimtarë, e u frikësuam se ai do t'i shpie ata të dy në humbje e në mosbesim.",
		81: "Deshëm që Zoti i tyre t'u japë në vend të tij një më të mirë se ai dhe më të afërt në respekt dhe në mëshirë (ndaj prindërve).",
		82: "Përsa i përket murit, ai ishte i dy djelmoshave jetima të atij qyteti, e nën të ata kishin një thesar (ari) dhe babai i tyre ka qenë njeri i mirë, e Zoti yt dëshiroi që ata dy (jetima) ta arrijnë pjekurinë e vet dhe ta nxjerrin ata vetë thesarin e tyre. Kjo ishte mëshirë e Zotit tënd (ndaj tyre). Dhe unë nuk e punova tërë atë sipas bindjes sime (po sipas udhëzimit të Zotit). Ky, pra, është sqarimi i asaj për të cilën nuk munde të kesh durim!",
		83: "Të pyesin ty për Dhulkarnejnin, thuaju: 'Do t'ju rrëfej për punën e tij me Kur'an (me shpallje)'",
		84: "Ne i mundësuam atij forcë në tokë dhe i dhamë mundësi për çdo send që të mund ta arrijë.",
		85: "Ai iu rrek një aso mundësie (dhe mori rrugën nga Perëndimi).",
		86: "Deri kur arriti në vendperëndimin e diellit, e gjeti se po perëndon në njëfarë burimi me lym të zi dhe aty e gjeti një popull. E Ne i thamë: 'O Dhulkarnejn, ose do t'i dënosh, ose do t'i marrish me të mirë e t'i udhëzosh!'",
		87: "Ai (Dhulkarnejni) tha: 'Ai që vazhdon edhe më tej të jetë zullumqar, atë do ta dënojmë, pastaj i kthehet Zotit të vet e Ai e dënon atë me një dënim të tmerrshëm'.",
		88: "Sa i përket atij që besoi dhe bëri vepra të mira, atij i takon shpërblimi më i mirë (xhenneti) dhe atij nga ana Jonë do t'i bëjmë lehtësi (në jetë).",
		89: "Pastaj, ai iu rrek një aso mundësie (mori rrugën e lindjes).",
		90: "Deri kur arriti vndlindjen e diellit, e gjeti se po lind mbi një popull, që nuk i kemi dhënë ndonjë mbulojë prej tij (diellit).",
		91: "Ashtu (bëri edhe me këtë popull), e Ne e kemi ditur gjendjen e tij (mundësitë dhe sundimin e drejtë të tij).",
		92: "Mandej, ai iu rrek përsëri një aso mundësie (një rruge të tretë mes perëndimit e lindjes - nga veriu).",
		93: "Deri kur arriti mes dy kodrave (si penda) dhe prapa tyre gjeti një popull që thuajse nuk kuptonte asnjë gjuhë (përveç gjuhës së vet).",
		94: "Ata thanë: 'O Dhulkarnejn, vërtet Jexhuxhi dhe Mexhuxhi janë duke bërë shkatërrime në tokë, a bën që ne të japim ty një kontribut (në formë tagre a tatimi), e që të bësh një pendë mes nesh dhe mes tyre?'",
		95: "Ai (Dhulkarnejni) tha: 'Atë që mua ma mundësoi Zoti im është shumë më i mirë (nga ajo që ma ofroni ju), po ju më ndihmoni me fuqi punëtore të bëj një pendë të fortë mes jush dhe mes atyre!'",
		96: "Më sillni copa të hekurit! E kur e nivelizoi ai me dy anët e kodrave, tha: 'Ndizni!', e kur e bëri atë (hekurin) zjarr (si zjarr nga të ndezurit) tha: 'Më sillni bakër të shkrirë t'ia hedhë atij!'",
		97: "E ata as nuk arritën ta kapërcenin atë e as ta shponin.",
		98: "Ai (Dhulkarnejni) tha: 'Kjo është një e mirë nga Zoti im, e kur të vjen caktimi i Zotit tim, Ai e bën atë rrafsh, e caktimi i Zotit tim është i sigurt.'",
		99: "(Kur të vijë caktimi i Zotit, ose kur të dalin Jexhuxh Mexhuxhët) Ne bëjmë atë ditë që ata të përzihen si valët njëra me tjetrën. Dhe i fryhet Surit (për herën e dytë) e të gjithë ata i tubojmë.",
		100: "Atë ditë ua prezentojmë xhehennemin jobesimtarëve me një prezentim të hapët (trishtues).",
		101: "Atyre që sytë i kishin të mbuluara ndaj argumenteve të Mia dhe që nuk mund të dëgjonin (fjalët e All-llahut).",
		102: "A mos menduan ata që nuk besuan se përkundër Meje mund të marrin zota (mbrojtës) robtë e Mi? Ne e kemi përgatitur për jobesimtarët xhehennemin vendpritje.",
		103: "Thuaj: 'A t'ju tregojmë për më të dëshpëruarit në veprat e tyre?'",
		104: "Ata janë veprimi i të cilëve u asgjësua në jetën e kësaj bote, e megjithatë ata mendojnë se janë kah bëjnë mirë.",
		105: "Të tillët janë ata që nuk besuan argumentet e Zoti të tyre as takimin (ringjalljen) e Tij, andaj veprat e tyre shkuan huq dhe në ditën e gjykimit atyre nuk do t'u japim kurrfarë vlere.",
		106: "Këtë, ngase shpërblimi i tyre është xhehennemi, për shkak se nuk besuan dhe argumentet e Mia e të dërguarit e Mi i morën për tallje.",
		107: "S'ka dyshim se ata që besuan dhe bënë vepra të mira, vendpritje për ta janë xhennetet e Firdevsit.",
		108: "Aty do të jenë përgjithmonë, e nuk kërkojnë të largohen nga ai (ose t'u ndryshohet).",
		109: "Thuaj: 'Sikur të ishte deti ngjyrë për t'i shkruar fjalët e Zotit tim, deti (uji i tij) do të shterej para se të përfundojnë fjalët e Zotit tim, e edhe sikur të sillnim shtesë edhe një si ai (deti)'.",
		110: "Thuaj: 'Unë jam vetëm njeri, sikurse edhe ju, mua më shpallet se vetëm një Zot është Zoti juaj, e kush është që e shpreson takimin e Zotit të vet, le të bëjë vepër të mirë, e në adhurimin ndaj Zotit të tij të mos e përziejë askë'.",
	},
	arabic: {
		0: "Bismilahirr-Rrahmanirr-Rrahim",
		1: "El hamdu lil-lahil-ledhi enzele ala abdihil kitabe ve lem jexha’al lehu ivexha.",
		2: "Kajjimel li jundhira be’sen shedidem mil ledunhu ve jubeshiral mu’mininel-ledhine ja’melunes salihati enne lehum exhran hasena.",
		3: "Makithine fihi ebeda.",
		4: "Ve jundhiral-ledhine kaluttehadhellahu veleda.",
		5: "Ma lehum bihi min ilmiv ve la li abaihim keburat kelimeten tahruxhu min efvahihim ij jekulune il-la kedhiba.",
		6: "Fe leal-leke bahiun nefseke ala atharihim il lem ju’minu bi hadhel hadithi esefa.",
		7: "Inna xhealna ma alel erdi zinetel leha li nebluvehum ejjuhum ahsenu amela.",
		8: "Ve inna le xhailune ma alejha saijden xhuruza.",
		9: "Em hasibte enne as'habel kehfi ver rekijmi kanu min ajatina axheba.",
		10: "Idh evel fitjetu ilel kehfi fe kalu rabbena atina mil ledunke rahmetev ve hejji’ lena min emrina rasheda.",
		11: "Fe darabna ala adhanihim fil kehfi sinine adeda.",
		12: "Thumme beathnahum li na’leme ejjul hizbejni ahsa lima lebithu emeda.",
		13: "Nahnu nekussu alejke nebeehum bil hakk innehum fitjetun amenu bi rabbihim ve zidnahum huda.",
		14: "Ve rabatna ala kulubihim idh kamu fe kalu rabbuna rabbus semavati vel erdi len ned’uve min dunihi ilahel le kad kulna idhen shetata.",
		15: "Haulai kavmunettehadhu min dunihi aliheh lev la jetune alejhim bi sultanim bejjin fe men adhlemu mimmeniftera alellahi kedhiba.",
		16: "Ve idhi’tezeltumuhum ve ma ja’budune il-lallahe fe’vu ilel kehfi jenshur lekum rabbukum mir rahmetihi ve juhejji’ lekum min emrikum mirfeka.",
		17: "Ve terash shemse idha taleat tezaveru an kehfihim dhatel jemini ve idha garabet takriduhum dhatesh shimali ve hum fi fexhvetim minh dhalike min ajetil-lah mej jehdil-lahu fe huvel muhted ve mej judlil fe len texhide lehu velijjem murshida.",
		18: "Ve tahsebuhum ejkadhav ve hum rukuduv ve nukal-libuhum dhatel jemini ve dhatesh shimali ve kelbuhum basitun dhiraajhi bil vesijd levit tala’te alejhim le vel-lejte minhum firarav ve le muli’te minhum ru’ba.",
		19: "Ve kedhalike beathnahum li jetesaelu bejnehum kale kailum minhum kem lebithtum kale lebithna jevmen ev ba'da jevm kalu rabbukum a'lemu bi ma lebithtum feb’athu ehadekum bi verkikum hadhihi ilel medineti fel jendhur ejuha ezka taamen fel je'tikum bi rizkim minhu vel jetelattaf ve la jush’iranne bikum ehada.",
		20: "Innehum ij jadhheru alejkum jerxhumukum ev juijdukum fi mil-letihim ve len tuflihu idhen ebeda.",
		21: "Ve kedhalike a’therna alejhim li ja’lemu enne va’dellahi hakkuv ve ennes saate la rejbe fiha idh jetenazeune bejnehum emrahum fe kalubnu alejhim bunjana rabbuhum a'lemu bihim kalel-ledhine galebu ala emrihim le nettehidhenne alejhim mesxhida.",
		22: "Se jekulune thelathetur rabiuhum kelbuhum ve jekulune hamsetun sadisuhum kelbuhum raxhmem bil gajb ve jekulune seb'atuv ve thaminuhum kelbuhum kur rabbi a’lemu bi iddetihim ma ja’lemuhum il-la kalilun fe la tumari fihim il-la miraen dhahirav ve la testefti fihim minhum ehada.",
		23: "Ve la tekulenne li shej’in inni failun dhalike gada.",
		24: "Il-la ej jeshaellahu vedhkur rabbeke idha nesite ve kul asa ej jehdijeni rabbi li akrabe min hadha rasheda.",
		25: "Ve lebithu fi kehfihim thelathe mietin sinine vezdadu tis’a.",
		26: "Kulil-lahu a’lemu bima lebithu lehu gajbus semavati vel erd ebthir bihi ve esmi ma lehum min dunihi miv velijjiv ve la jushriku fi hukmihi ehada.",
		27: "Vetlu ma uhije ilejke min kitabi rabbik la mubbeddile li kelimatihi ve len texhide min dunihi multehada.",
		28: "Vasbir nefseke meal-ledhine jed’une rabbehum bil gadati vel ashijji juridune vexhhehu ve la ta’du ajnake anhum turidu zinetel hajatid dunja ve la tuti men agfelna kalbehu an dhikrina vettebea hevahu ve kane emruhu furuta.",
		29: "Ve kulil hakku mir rabbikum fe men shae fel ju’miv ve men shae fel jekfur inna a’tedna lidh-dhalimine naran ehata bihim suradikuha ve ij jestegijthu jugathu bi main kel muhli jeshvil vuxhuh bi’sesh sherabu ve saet murtefeka.",
		30: "Innel-ledhine amenu ve amilus salihati inna la nudij’u exhra men ahsene amela.",
		31: "Ulaike lehum xhennatu adnin texhri min tahtihimul enharu juhal-levne fiha min esavira min dhehebiv ve jelbesune thijaben hudram min sundusiv ve istebrakim muttekiine fiha alel eraik ni’meth-thevab ve hasunet murtefeka",
		32: "Vadrib lehum metheler raxhulejni xhealna li ehadihima xhennetejni min a’nabiv ve hafefnahuma bi nahliv ve xhealna bejnehuma zer’a.",
		33: "Kiltel xhenetejni atet ukuleha ve lem tadhlim minhu shej’ev ve fexherna hilalehuma nehera.",
		34: "Ve kane lehu themer fe kale li sahibihi ve huve juhaviruhu ene ektheru minke malev ve eazzu nefera.",
		35: "Ve dehale xhennetehu ve huve dhalimul li nefsih kale ma edhunnu en tebide hadhihi ebeda.",
		36: "Ve ma edhunnus saate kaimetev ve leir rudidtu ila rabbi le exhidenne hajram minha munkaleba.",
		37: "Kale lehu sahibuhû ve huve juhaviruhu e keferte bil-ledhi halekake min turabin thumme min nutfetin thumme sevvake raxhula.",
		38: "Lakinne huvellahu rabbi ve la ushriku bi rabbi ehada.",
		39: "Ve lev la idh dehalte xhenneteke kulte ma shaellahu la kuvvete il-la bil-lah in terani ene ekal-le minke malev ve veleda.",
		40: "Fe asa rabbi ej ju’tijeni hajram min xhennetike ve jursile alejha husbanem mines semai fe tusbiha saijden zeleka.",
		41: "Ev jusbiha mauha gavran fe len testeij’a lehu taleba.",
		42: "Ve uhijta bi themerihi fe asbeha jukal-libu keffejhi ala ma enfeka fiha ve hije havijetun ala urushiha ve jekulu ja lejteni lem ushrik bi rabbi ehada.",
		43: "Ve lem tekul lehu fietuj jensurunehu min dunil-lahi ve ma kane muntesira.",
		44: "Hunalikel velajetu lil-lahil hakk huve hajrun thevabev ve hajrun ukba.",
		45: "Vadrib lehum methelel hajatid dunja ke main enzelnahu mines semai fahteleta bihi nebatul erdi fe asbeha heshimen tedhruhur rijah ve kanellahu ala kul-li shej’im muktedira.",
		46: "Elmalu vel benune zinetul hajatid dunja vel bakijatus salihatu hajrun inde rabbike thevabev ve hajrun emela.",
		47: "Ve jevme nusejjirul xhibale ve teral erda barizetev ve hashernahum fe lem nugadir minhum ehada.",
		48: "Ve uridu ala rabbike saffa le kad xhi’tumuna kema halaknakum evvele mer-ratim bel zeamtum el-len nexh’ale lekum mev’ida.",
		49: "Ve vudial kitabu fe teral muxhrimine mushfikine mimma fihi ve jekulune ja vejletena mali hadhel kitabi la jugadiru sagijratev ve la kebiraten il-la ahsaha ve vexhedu ma amilu hadira ve la jadhlemu rabbuke ehada.",
		50: "Ve idh kulna lil melaiketisxhudu li ademe fe sexhedu il-la iblis kane minel xhinni fe feseka an emri rabbih e fe tetehidhunehu ve dhurijjetehu evlijae min duni ve hum lekum adduvv bi’se lidh dhalimine bedela.",
		51: "Ma esh-hedtuhum halkas semavati vel erdi ve la halka enfusihim ve ma kuntu muttehidhel mudiline aduda.",
		52: "Ve jevme jekulu nadu shurakaijel-ledhine zeamtum fe deavhum fe lem jestexhibu lehum ve xhealna bejnehum mevbika.",
		53: "Verael muxhrimunen nara fe dhanu ennehum muvakiuha ve lem jexhidu anha masrifa.",
		54: "Ve le kad sar-rafna fi hadhel kur’ani lin nasi min kul-li methel ve kanel insane ekthera shej’in xhedela.",
		55: "Ve ma menean nase ej ju’minu idh xhaehumul huda ve jestagfiru rabbehum il-la en te’tijehum sunnetul evveline ev je’tijehumul adhabu kubula.",
		56: "Ve ma nursilul murseline il-la mubeshirine ve mundhirin ve juxhadilul-ledhine keferu bil batili li jud-hidu bihil hakka vettehadhu ajati ve ma undhiru huzuva.",
		57: "Ve men adhlemu mimmen dhukkira bi ajati rabbihi fe a’arada anha ve nesije ma kaddemet jedah inna xhealna ala kulubihim ekinneten ej jefkahuhu ve fi adhanihim vakra ve in ted’uhum ilel huda fe lej jehtedu idhen ebedâ.",
		58: "Ve rabbukel gafuru dhur rahmeh lev juahidhuhum bi ma kesebu le axhele lehumul adhab bel lehum mev’idul lej jexhidu min dunihi mev’ila.",
		59: "Ve tilkel kura ehleknahum lemma dhalemu ve xhealna li mehlikihim mev’ida.",
		60: "Ve idh kale musa li fetahu la ebrahu hatta ebluga mexhmeal bahrajni ev emdije hukuba.",
		61: "Felemma belega mexhmea bejnihima nesija hutehuma fettehadhe sebilehu fil bahri seraba.",
		62: "Felemma xhaveza kaleli fetahu atina gadaena le kad lekijna min seferina hadha nesaba.",
		63: "Kale eraejte idh evejna iles sahrati fe inni nesitul hute ve ma ensanihu il-lesh shejtanu en edhkurah vet-tehadhe sebilehu fil bahri axheba.",
		64: "Kale dhalike ma kunna nebgi fertedda ala atharihima kasasa.",
		65: "Fe vexheda abdem min ibadina atejnahu rahmetem min indina ve al-lemnahu mil leddunna ilma.",
		66: "Kale lehu musa hel ettebiuke ala an tual-limeni mimma ul-limte rushda.",
		67: "Kale inneke len testetij'a meije sabra.",
		68: "Ve kejfe tasbiru ala ma lem tuhit bihi hubra.",
		69: "Kale setexhiduni in shaellahu sabirav ve la a'sij leke emra.",
		70: "Kale fe initteba'teni fe la tes'eleni an shej'in hatta uhdithe leke minhu dhikra.",
		71: "Fentaleka hatta idha rakiba fis sefineti harakaha kale eharakteha li tugrika ehleha le kad xhi’te shej’en imra.",
		72: "Kale e’lem e kul inneke len testetij’a meije sabra.",
		73: "Kale la tuahidhni bima nesitu ve la turhikni min emri usra.",
		74: "Fentaleka hatta idha lekija gulamen fe katelehu kale e katelte nefsen zekijjetem bi gajri nefs le kad xhi’te shej’en nukra.",
		75: "Kale elem e kul leke inneke len testetij’a meije sabra.",
		76: "Kale in seeltuke an shej’im ba’deha fe la tusahibni kad belagte mil ledunni udhra.",
		77: "Fentaleka hatta idha eteja ehle karjetinistet’ama ehleha fe ebev ej judajjifuhuma fevexheda fiha xhidaraj juridu ej jenkadda fe ekameh kale lev shi’te lettehadhte alejhi exhra.",
		78: "Kale hadha firaku bejni ve bejnik se unebbiuke bi te’vili ma lem testeti’ alejhi sabra.",
		79: "Emmes sefinetu fe kanet li mesakine ja’melune fil bahri fe eradtu en eijbeha ve kane veraehum melikuj je’hudhu kul-le sefinetin gasba.",
		80: "Ve emmel gulamu fekane ebevahu mu'minejni fe hashina ej jurhikahuma tugjanev ve kufra.",
		81: "Fe eradna ej jubdilehuma rabbuhuma hajram minhu zekatev ve akrabe ruhma.",
		82: "Ve emmel xhidaru fe kane li gulamejni jetimejni fil medineti ve kane tahtehu kenzul lehuma ve kane ebuhuma saliha fe erade rabbuke ej jebluga eshuddehuma ve jestahrixha kenzehuma rahmetem mir rabbik ve ma fealtuhu an emri dhalike te’vilu ma lem testi’ alejhi sabra.",
		83: "Ve jes’eluneke an dhil karnejni kul seetlu alejkum minhu dhikra.",
		84: "Inna mekkenna lehu fil erdi ve atejnahu min kul-li shej’in sebeba.",
		85: "Fe etbea sebeba.",
		86: "Hatta idha belega magribesh shemsi vexhedeha tagrubu fi ajnin hamietiv ve vexhede indeha kavma kulna jadhel karnejni imma an tuadhibe ve imma an tetehidhe fihim husna.",
		87: "Kale emma men dhaleme fe sevfe nuadhibuhu thumme juraddu ila rabbihi fejuadhibuhu adhaben nukra.",
		88: "Ve emma men amen ve amile salihan fe lehu xhezaenil husna ve senekulu lehu min emrina jusra.",
		89: "Thumme etbea sebeba.",
		90: "Hatta idha belaga matliash shemsi vexhedeha tatluu ala kavmil lem nexh’al lehum min duniha sitra.",
		91: "Kedhalike ve kad ehatna bima ledejhi hubra.",
		92: "Thumme etbea sebeba.",
		93: "Hatta idha belaga bejnes seddejni vexhede min dunihima kavmel la jekadune jefkahune kavla.",
		94: "Kalu ja dhel karnejni inne je’xhuxhe ve me’xhuxhe mufisidune fil erdi fe hel nexh’alu leke harxhen ala an texh’ale bejnena ve bejnehum sedda.",
		95: "Kale ma mekkenni fihi rabbi hajrun fe eijnuni bi kuvvetin exh’al bejnekum ve bejnehum redma.",
		96: "Atuni zuberal hadid hatta idha sava bejnes sadafejni kalenfuhu hatta idha xhealehu naran kale atuni ufrig alejhi kidra.",
		97: "Femestau ej jadh-heruhu ve mestatu lehu nakba.",
		98: "Kale hadha rahmetum mir rabbi fe idha xhae va’du rabbi xhealehu dekka ve kane a’du rabbi hakka.",
		99: "Ve terakna ba’dahum jevmeidhij jemuxhu fi ba’div ve nufiha fis suri fe xhema’nahum xhem’a.",
		100: "Ve aradna xhehenneme jevmeidhil lil kafirine arda.",
		101: "El-ledhine kanet a’junuhum fi gitain an dhikri ve kanu la jestetij’une sem’a.",
		102: "E fe hasibel-ledhine keferu ej jettehidhu ibadi min duni evlija’ inna a’tedna xhehenneme lil kafirine nuzula.",
		103: "Kul hel nunebbiukum bil ahserine a’mala.",
		104: "El-ledhine dale sa’juhum fil hajatid dunja ve hum jahsebune ennehum juhsinune sun’a.",
		105: "Ulaikel-ledhine keferu bi ajati rabbihim ve likaihi fe habitat a’maluhum fe la nukijmu lehum jevmel kijameti vezna.",
		106: "Dhalike xhezauhum xhehennemu bima keferu vettehadhu ajati ve rusuli huzuva.",
		107: "Innel-ledhine amenu ve amilus salihati kanet lehum xhennatul firdevsi nuzula.",
		108: "Halidine fiha la jebgune anha hivela.",
		109: "Kul lev kanel bahru midadel li kelimati rabbi le nefidel bahru kable en tenfede kelimatu rabbi ve lev xhi'na bi mithlihi mededa.",
		110: "Kul innema ene besherum mithlukum juha ilejje enema ilahukum ilahuv vahid fe men kane jerxhu likae rabbihi felja’mel amelen salihav ve la jushrik bi ibadeti rabbihi ehada.",
	},
};
